AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Todo Application

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: todo-api
        LOG_LEVEL: INFO

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-todos'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TodoUserPoolClient:
    Type: AWS::Serverless::Function
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref TodoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_todo/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: post

  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_todos/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Events:
        GetTodos:
          Type: Api
          Properties:
            Path: /todos
            Method: get

    UpdateTodoFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/update_todo/
        Handler: app.lambda_handler
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
        Events:
          UpdateTodo:
            Type: Api
            Properties:
              Path: /todos/{taskId}
              Method: put
  
    DeleteTodoFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/delete_todo/
        Handler: app.lambda_handler
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
        Events:
          DeleteTodo:
            Type: Api
            Properties:
              Path: /todos/{taskId}
              Method: delete

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref TodoUserPool

  UserPoolCLientId:
    Description: Cognito User Pool Client ID
    Value: !Ref TodoUserClientPool
    
  TodoTableName:
    Description: DynamoDB Table Name
    Value: !Ref TodoTable

  TodoTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt TodoTable.Arn

  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
